import{a as L,S as w,i as p}from"./assets/vendor-DEenWwFD.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const h=r=>`
      <li class="gallery-card">
        <a href="${r.largeImageURL}" class="gallery-link">
          <img class="gallery-img" src="${r.webformatURL}" alt="${r.tags}"/>
        </a>
        <ul class="info-card-list">
            <li class="info-card-item">Likes <p> ${r.likes} </p></li>
            <li class="info-card-item">Views <p>${r.views}</p></li>
            <li class="info-card-item">Comments <p>${r.comments}</p></li>
            <li class="info-card-item">Downloads <p>${r.downloads}</p></li>
        </ul>
      </li>

    `,y=(r,o)=>{const s={params:{key:"48308646-4d458c48d5d2f9bc699dc7008",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}};return L.get("https://pixabay.com/api/",s)},g=document.querySelector(".js-search-form"),d=document.querySelector(".js-gallery"),u=document.querySelector(".gallery-load"),a=document.querySelector(".js-btn-load-more");let i=1,c="";const b=async r=>{try{if(r.preventDefault(),c=r.currentTarget.elements.user_gallery.value.trim(),c===""){p.show({message:"❌ Sorry, search field is empty. Please, try again!",color:"red",position:"topRight"});return}d.innerHTML="",g.reset(),(()=>{u.classList.remove("hidden")})(),i=1,a.classList.add("is-hidden");const s=await y(c,i);(()=>{u.classList.add("hidden")})();const e=s.data.hits.map(n=>h(n)).join("");d.innerHTML=e,f.refresh(),s.data.hits.length===0&&p.show({message:"❌ Sorry, there are no images matching your search query. Please, try again!",color:"red",position:"topRight"});const t=i*15;s.data.totalHits>t&&(a.classList.remove("is-hidden"),a.removeEventListener("click",m),a.addEventListener("click",m))}catch(o){console.log(o)}};g.addEventListener("submit",b);const m=async r=>{try{i++;const o=await y(c,i),s=o.data.hits.map(t=>h(t)).join("");d.insertAdjacentHTML("beforeend",s),f.refresh();const{height:l}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:l*2,behavior:"smooth"}),i*15>=o.data.totalHits&&(a.classList.add("is-hidden"),a.removeEventListener("click",m),p.show({message:"We're sorry, but you've reached the end of search results.",color:"blue",position:"topRight"}))}catch(o){console.log(o)}};let f=new w(".gallery-link",{captionsData:"alt",captionDelay:250});
//# sourceMappingURL=index.js.map
